version: '3'
services:
  iota:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    command: ash -c "npm i && npm run build-index && npm run start"
    ports:
      - '3000:3000'
    volumes:
      - .:/app
